[PARSER]
    Name        suricata_json
    Format      json
    Time_Key    timestamp
    Time_Format %Y-%m-%dT%H:%M:%S.%L

[PARSER]
    Name        ntopng_json
    Format      json
    Time_Key    time
    Time_Format %s

[PARSER]
    Name        opnsense_syslog
    Format      regex
    Regex       ^<(?<pri>[0-9]+)>(?<timestamp>[^ ]+) (?<host>[^ ]+) (?<tag>[^:]+): (?<message>.*)$
    Time_Key    timestamp
    Time_Format %b %d %H:%M:%S
